name: sum_ffi
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  ffi: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
